component: http
name: thinkphpDemo

inputs:
  src: ./
  region: ap-guangzhou
  faas:
    name: ${name}
    framework: thinkphp
    runtime: Php7
    environments:
      - key: APP_ENV
        value: production
  apigw:
    protocols:
      - http
      - https
