app: appDemo
stage: dev

component: django@dev
name: djangoDemo

inputs:
  src:
    hook: 'pip3 install -r requirements.txt -t ./'
    dist: ./
    exclude:
      - .env
      - 'requirements/**'
      - '__pycache__/**'
  region: ap-guangzhou
  faas:
    startCmd: python manage.py runserver --noreload 9000
    serverPort: 9000
    name: ${name}
    runtime: Python3.6
  apigw:
    protocols:
      - http
      - https
    environment: release
