component: http
name: djangoDemo

inputs:
  src:
    # 这里会自动帮你安装依赖到当前项目根目录
    hook: 'pip3 install -r requirements.txt -t ./'
    dist: ./
    exclude:
      - .env
      - '__pycache__/**'
  region: ap-guangzhou
  faas:
    framework: django
    name: ${name}
    runtime: Python3.6
    memorySize: 512
  apigw:
    protocols:
      - http
      - https
