app: appDemo
stage: dev

component: nestjs@dev
name: nestDemo

inputs:
  src:
    src: ./
    exclude:
      - .env
  functionConf:
    name: ${name}
  apigatewayConf:
    protocols:
      - http
      - https
